# Generated by Django 5.1.5 on 2026-03-24 18:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WalletAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_balance', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=20)),
                ('initial_cash', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=20)),
                ('net_cash_flow', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='wallet.telegramidentity')),
            ],
        ),
        migrations.CreateModel(
            name='TestOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=8)),
                ('asset_id', models.CharField(choices=[('USDt', 'USDt'), ('TSLAx', 'TSLAx'), ('HOODx', 'HOODx'), ('AMZNx', 'AMZNx'), ('NVDAx', 'NVDAx'), ('COINx', 'COINx'), ('GOOGLx', 'GOOGLx'), ('AAPLx', 'AAPLx'), ('MSTRx', 'MSTRx')], max_length=16)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('notional', models.DecimalField(decimal_places=6, max_digits=20)),
                ('status', models.CharField(choices=[('filled', 'Filled')], default='filled', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='wallet.walletaccount')),
            ],
        ),
        migrations.CreateModel(
            name='AgentPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_agents', models.JSONField(default=list)),
                ('allocation', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_preference', to='wallet.walletaccount')),
            ],
        ),
        migrations.CreateModel(
            name='AssetPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(choices=[('USDt', 'USDt'), ('TSLAx', 'TSLAx'), ('HOODx', 'HOODx'), ('AMZNx', 'AMZNx'), ('NVDAx', 'NVDAx'), ('COINx', 'COINx'), ('GOOGLx', 'GOOGLx'), ('AAPLx', 'AAPLx'), ('MSTRx', 'MSTRx')], max_length=16)),
                ('quantity', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20)),
                ('average_entry_price', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='wallet.walletaccount')),
            ],
            options={
                'unique_together': {('account', 'asset_id')},
            },
        ),
    ]
