# Generated by Django 5.1.5 on 2026-03-24 21:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_add_session_token_to_pending_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingauth',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pendingauth',
            name='session_token',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='pendingauth',
            name='telegram_user_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='AssetPriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(choices=[('USDt', 'USDt'), ('TSLAx', 'TSLAx'), ('HOODx', 'HOODx'), ('AMZNx', 'AMZNx'), ('NVDAx', 'NVDAx'), ('COINx', 'COINx'), ('GOOGLx', 'GOOGLx'), ('AAPLx', 'AAPLx'), ('MSTRx', 'MSTRx')], max_length=16)),
                ('price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('observed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('source', models.CharField(default='fmp', max_length=32)),
            ],
            options={
                'indexes': [models.Index(fields=['asset_id', '-observed_at'], name='wallet_asse_asset_i_f126f2_idx')],
            },
        ),
    ]
