# Generated by Django 5.1.5 on 2026-03-24 21:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_pendingauth_completed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(choices=[('USDt', 'USDt'), ('TSLAx', 'TSLAx'), ('HOODx', 'HOODx'), ('AMZNx', 'AMZNx'), ('NVDAx', 'NVDAx'), ('COINx', 'COINx'), ('GOOGLx', 'GOOGLx'), ('AAPLx', 'AAPLx'), ('MSTRx', 'MSTRx')], max_length=16)),
                ('remaining_quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('entry_price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('opened_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_lots', to='wallet.walletaccount')),
            ],
            options={
                'indexes': [models.Index(fields=['account', 'asset_id', 'opened_at'], name='wallet_posi_account_dd15d0_idx')],
            },
        ),
    ]
