# Generated by Django 5.2.12 on 2026-03-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_agentpreference_onboarding_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='testorder',
            name='realized_pnl',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=20, null=True),
        ),
    ]
