# Generated by Django 5.1.5 on 2026-03-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_testorder_realized_pnl'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotJsonEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, default='telegram_bot', max_length=32)),
                ('category', models.CharField(db_index=True, max_length=64)),
                ('telegram_update_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('telegram_user_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('chat_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
